### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'astype'

### ISSUE THREAD

**Issue by yanxiangyi** [facebookresearch/DetectAndTrack#34]
Hi @rohitgirdhar, I'm now trying to run the training code.

However, when I run this:

```python launch.py -c configs/video/2d_best/01_R101_best_hungarian-4GPU.yaml```

The error is like:

```
INFO train_net.py: 144: Outputs saved to: /mnt/data/xiangyiy/Repository/DetectAndTrack/outputs/configs/video/2d_best/01_R101_best_hungarian-4GPU.yaml/train/posetrack_v1.0_train/keypoint_rcnn
Traceback (most recent call last):
  File "/mnt/data/xiangyiy/Repository/DetectAndTrack/lib/utils/coordinator.py", line 41, in stop_on_exception
    yield
  File "/mnt/data/xiangyiy/Repository/DetectAndTrack/lib/roi_data/loader.py", line 209, in minibatch_loader2
    shared_readonly_dict, lock, mp_cur, mp_perm)
  File "/mnt/data/xiangyiy/Repository/DetectAndTrack/lib/roi_data/loader.py", line 161, in _get_next_minibatch2
    blobs, valid = get_minibatch(minibatch_db)
  File "/mnt/data/xiangyiy/Repository/DetectAndTrack/lib/roi_data/minibatch.py", line 56, in get_minibatch
    im_blob, im_scales = _get_image_blob(roidb)
  File "/mnt/data/xiangyiy/Repository/DetectAndTrack/lib/roi_data/minibatch.py", line 84, in _get_image_blob
    im, cfg.PIXEL_MEANS, [target_size], cfg.TRAIN.MAX_SIZE)
  File "/mnt/data/xiangyiy/Repository/DetectAndTrack/lib/utils/blob.py", line 73, in prep_im_for_blob
    im = im.astype(np.float32, copy=False)
AttributeError: 'NoneType' object has no attribute 'astype'
```

**Comment by yanxiangyi** [comment]
Solved. This is because the net is feed by no img data. Just following the `README.md` to use `tools/gen_posetrack_json.py` and changing paths in `lib/datasets/json_dataset.py` would solve this.

**Comment by Marcovaldong** [comment]
@yanxiangyi How did you process data by tools/gen_posetrack_json.py? Why should not we use json files provided by the repo? TKS

**Comment by ezreal1129** [comment]
@yanxiangyi   i have the same problem,and i used the gen_posetrack_json.py  can you post your json_dataset.py? thanks a lot.

**Comment by yanxiangyi** [comment]
Same with #34 . This is because the net is feed by no img data. Just following the `README.md` to use `tools/gen_posetrack_json.py`.

Your `IM_DIR` should be the directory to your renamed images. For me, it's 
```
'posetrack_v1.0_train': {
        IM_DIR: 'lib/datasets/data/PoseTrack/posetrack_data/images_renamed/',
        ANN_FN: 'lib/datasets/lists/PoseTrack/v1.0/posetrack_train.json',
        # ANN_DN: 'lib/datasets/data/PoseTrackV1.0_Annots_train_json/',
    }
```
and so on so forth.
