### ISSUE TITLE
RuntimeError: [enforce fail at pybind_state.cc:1096] success. Error running net keypoint_rcnn

### ISSUE THREAD

**Issue by Marcovaldong** [facebookresearch/DetectAndTrack#35]
I tried to run the command to train the model by myself, then I got errors velow:

```
loading annotations into memory...
Done (t=1.65s)
creating index...
index created!
INFO roidb.py:  34: Appending horizontally-flipped training examples...
INFO roidb.py:  36: Loaded dataset: posetrack_v1.0_train
INFO roidb.py: 116: Filtered 43940 roidb entries: 59404 -> 15464
Video-fying the roidb:   0%|                                      | 0/15464 [00:00<?, ?it/s]/data/weiming.li/.pyenv/versions/anaconda2-5.2.0/lib/python2.7/site-packages/scipy/sparse/compressed.py:746: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  SparseEfficiencyWarning)
Video-fying the roidb: 100%|██████████████████████████| 15464/15464 [03:12<00:00, 80.25it/s]
INFO video.py: 200: Video-fied roidb contains 14458 elements
INFO roidb.py:  56: Computing bounding-box regression targets...
INFO roidb.py:  58: done
INFO roidb.py: 173: Ground-truth class histogram:
INFO roidb.py: 177: 0__background__: 0
INFO roidb.py: 177: 1        person: 99792
INFO roidb.py: 178: --------------
INFO roidb.py: 181:          total: 99792
INFO train_net.py: 118: 14458 roidb entries
INFO net.py: 165: Loading from: ./pretrained_models/ResNet18_weights.pkl
INFO net.py: 204: conv1_w loaded from weights file into gpu_0/conv1_w: (64, 3, 7, 7)
WARNING net.py: 150: Workspace blob conv1_w ((64, 3, 1, 7, 7)) loaded with pretrained wts (64, 3, 7, 7) after inflating the weights by center-only mode.
INFO net.py: 204: res_conv1_bn_s loaded from weights file into gpu_0/res_conv1_bn_s: (64,)
INFO net.py: 204: res_conv1_bn_b loaded from weights file into gpu_0/res_conv1_bn_b: (64,)
INFO net.py: 204: res2_0_branch2a_w loaded from weights file into gpu_0/res2_0_branch2a_w: (64, 64, 3, 3)
WARNING net.py: 150: Workspace blob res2_0_branch2a_w ((64, 64, 1, 3, 3)) loaded with pretrained wts (64, 64, 3, 3) after inflating the weights by center-only mode.
INFO net.py: 204: res2_0_branch2a_bn_s loaded from weights file into gpu_0/res2_0_branch2a_bn_s: (64,)
INFO net.py: 204: res2_0_branch2a_bn_b loaded from weights file into gpu_0/res2_0_branch2a_bn_b: (64,)
INFO net.py: 204: res2_0_branch2b_w loaded from weights file into gpu_0/res2_0_branch2b_w: (64, 64, 3, 3)
WARNING net.py: 150: Workspace blob res2_0_branch2b_w ((64, 64, 1, 3, 3)) loaded with pretrained wts (64, 64, 3, 3) after inflating the weights by center-only mode.
INFO net.py: 204: res2_0_branch2b_bn_s loaded from weights file into gpu_0/res2_0_branch2b_bn_s: (64,)
INFO net.py: 204: res2_0_branch2b_bn_b loaded from weights file into gpu_0/res2_0_branch2b_bn_b: (64,)
INFO net.py: 204: res2_1_branch2a_w loaded from weights file into gpu_0/res2_1_branch2a_w: (64, 64, 3, 3)
WARNING net.py: 150: Workspace blob res2_1_branch2a_w ((64, 64, 1, 3, 3)) loaded with pretrained wts (64, 64, 3, 3) after inflating the weights by center-only mode.
INFO net.py: 204: res2_1_branch2a_bn_s loaded from weights file into gpu_0/res2_1_branch2a_bn_s: (64,)
INFO net.py: 204: res2_1_branch2a_bn_b loaded from weights file into gpu_0/res2_1_branch2a_bn_b: (64,)
INFO net.py: 204: res2_1_branch2b_w loaded from weights file into gpu_0/res2_1_branch2b_w: (64, 64, 3, 3)
WARNING net.py: 150: Workspace blob res2_1_branch2b_w ((64, 64, 1, 3, 3)) loaded with pretrained wts (64, 64, 3, 3) after inflating the weights by center-only mode.
INFO net.py: 204: res2_1_branch2b_bn_s loaded from weights file into gpu_0/res2_1_branch2b_bn_s: (64,)
INFO net.py: 204: res2_1_branch2b_bn_b loaded from weights file into gpu_0/res2_1_branch2b_bn_b: (64,)
INFO net.py: 204: res3_0_branch2a_w loaded from weights file into gpu_0/res3_0_branch2a_w: (128, 64, 3, 3)
WARNING net.py: 150: Workspace blob res3_0_branch2a_w ((128, 64, 3, 3, 3)) loaded with pretrained wts (128, 64, 3, 3) after inflating the weights by center-only mode.
INFO net.py: 204: res3_0_branch2a_bn_s loaded from weights file into gpu_0/res3_0_branch2a_bn_s: (128,)
INFO net.py: 204: res3_0_branch2a_bn_b loaded from weights file into gpu_0/res3_0_branch2a_bn_b: (128,)
INFO net.py: 204: res3_0_branch2b_w loaded from weights file into gpu_0/res3_0_branch2b_w: (128, 128, 3, 3)
WARNING net.py: 150: Workspace blob res3_0_branch2b_w ((128, 128, 3, 3, 3)) loaded with pretrained wts (128, 128, 3, 3) after inflating the weights by center-only mode.
INFO net.py: 204: res3_0_branch2b_bn_s loaded from weights file into gpu_0/res3_0_branch2b_bn_s: (128,)
INFO net.py: 204: res3_0_branch2b_bn_b loaded from weights file into gpu_0/res3_0_branch2b_bn_b: (128,)
INFO net.py: 204: res3_0_branch1_w loaded from weights file into gpu_0/res3_0_branch1_w: (128, 64, 1, 1)
WARNING net.py: 150: Workspace blob res3_0_branch1_w ((128, 64, 1, 1, 1)) loaded with pretrained wts (128, 64, 1, 1) after inflating the weights by center-only mode.
INFO net.py: 204: res3_0_branch1_bn_s loaded from weights file into gpu_0/res3_0_branch1_bn_s: (128,)
INFO net.py: 204: res3_0_branch1_bn_b loaded from weights file into gpu_0/res3_0_branch1_bn_b: (128,)
INFO net.py: 204: res3_1_branch2a_w loaded from weights file into gpu_0/res3_1_branch2a_w: (128, 128, 3, 3)
WARNING net.py: 150: Workspace blob res3_1_branch2a_w ((128, 128, 3, 3, 3)) loaded with pretrained wts (128, 128, 3, 3) after inflating the weights by center-only mode.
INFO net.py: 204: res3_1_branch2a_bn_s loaded from weights file into gpu_0/res3_1_branch2a_bn_s: (128,)
INFO net.py: 204: res3_1_branch2a_bn_b loaded from weights file into gpu_0/res3_1_branch2a_bn_b: (128,)
INFO net.py: 204: res3_1_branch2b_w loaded from weights file into gpu_0/res3_1_branch2b_w: (128, 128, 3, 3)
WARNING net.py: 150: Workspace blob res3_1_branch2b_w ((128, 128, 3, 3, 3)) loaded with pretrained wts (128, 128, 3, 3) after inflating the weights by center-only mode.
INFO net.py: 204: res3_1_branch2b_bn_s loaded from weights file into gpu_0/res3_1_branch2b_bn_s: (128,)
INFO net.py: 204: res3_1_branch2b_bn_b loaded from weights file into gpu_0/res3_1_branch2b_bn_b: (128,)
INFO net.py: 204: res4_0_branch2a_w loaded from weights file into gpu_0/res4_0_branch2a_w: (256, 128, 3, 3)
WARNING net.py: 150: Workspace blob res4_0_branch2a_w ((256, 128, 3, 3, 3)) loaded with pretrained wts (256, 128, 3, 3) after inflating the weights by center-only mode.
INFO net.py: 204: res4_0_branch2a_bn_s loaded from weights file into gpu_0/res4_0_branch2a_bn_s: (256,)
INFO net.py: 204: res4_0_branch2a_bn_b loaded from weights file into gpu_0/res4_0_branch2a_bn_b: (256,)
INFO net.py: 204: res4_0_branch2b_w loaded from weights file into gpu_0/res4_0_branch2b_w: (256, 256, 3, 3)
WARNING net.py: 150: Workspace blob res4_0_branch2b_w ((256, 256, 3, 3, 3)) loaded with pretrained wts (256, 256, 3, 3) after inflating the weights by center-only mode.
INFO net.py: 204: res4_0_branch2b_bn_s loaded from weights file into gpu_0/res4_0_branch2b_bn_s: (256,)
INFO net.py: 204: res4_0_branch2b_bn_b loaded from weights file into gpu_0/res4_0_branch2b_bn_b: (256,)
INFO net.py: 204: res4_0_branch1_w loaded from weights file into gpu_0/res4_0_branch1_w: (256, 128, 1, 1)
WARNING net.py: 150: Workspace blob res4_0_branch1_w ((256, 128, 1, 1, 1)) loaded with pretrained wts (256, 128, 1, 1) after inflating the weights by center-only mode.
INFO net.py: 204: res4_0_branch1_bn_s loaded from weights file into gpu_0/res4_0_branch1_bn_s: (256,)
INFO net.py: 204: res4_0_branch1_bn_b loaded from weights file into gpu_0/res4_0_branch1_bn_b: (256,)
INFO net.py: 204: res4_1_branch2a_w loaded from weights file into gpu_0/res4_1_branch2a_w: (256, 256, 3, 3)
WARNING net.py: 150: Workspace blob res4_1_branch2a_w ((256, 256, 3, 3, 3)) loaded with pretrained wts (256, 256, 3, 3) after inflating the weights by center-only mode.
INFO net.py: 204: res4_1_branch2a_bn_s loaded from weights file into gpu_0/res4_1_branch2a_bn_s: (256,)
INFO net.py: 204: res4_1_branch2a_bn_b loaded from weights file into gpu_0/res4_1_branch2a_bn_b: (256,)
INFO net.py: 204: res4_1_branch2b_w loaded from weights file into gpu_0/res4_1_branch2b_w: (256, 256, 3, 3)
WARNING net.py: 150: Workspace blob res4_1_branch2b_w ((256, 256, 3, 3, 3)) loaded with pretrained wts (256, 256, 3, 3) after inflating the weights by center-only mode.
INFO net.py: 204: res4_1_branch2b_bn_s loaded from weights file into gpu_0/res4_1_branch2b_bn_s: (256,)
INFO net.py: 204: res4_1_branch2b_bn_b loaded from weights file into gpu_0/res4_1_branch2b_bn_b: (256,)
INFO net.py: 196: conv_rpn_w not found
INFO net.py: 196: conv_rpn_b not found
INFO net.py: 196: rpn_cls_logits_1_w not found
INFO net.py: 196: rpn_cls_logits_1_b not found
INFO net.py: 196: rpn_bbox_pred_1_w not found
INFO net.py: 196: rpn_bbox_pred_1_b not found
INFO net.py: 204: res5_0_branch2a_w loaded from weights file into gpu_0/res5_0_branch2a_w: (512, 256, 3, 3)
WARNING net.py: 150: Workspace blob res5_0_branch2a_w ((512, 256, 1, 3, 3)) loaded with pretrained wts (512, 256, 3, 3) after inflating the weights by center-only mode.
INFO net.py: 204: res5_0_branch2a_bn_s loaded from weights file into gpu_0/res5_0_branch2a_bn_s: (512,)
INFO net.py: 204: res5_0_branch2a_bn_b loaded from weights file into gpu_0/res5_0_branch2a_bn_b: (512,)
INFO net.py: 204: res5_0_branch2b_w loaded from weights file into gpu_0/res5_0_branch2b_w: (512, 512, 3, 3)
WARNING net.py: 150: Workspace blob res5_0_branch2b_w ((512, 512, 1, 3, 3)) loaded with pretrained wts (512, 512, 3, 3) after inflating the weights by center-only mode.
INFO net.py: 204: res5_0_branch2b_bn_s loaded from weights file into gpu_0/res5_0_branch2b_bn_s: (512,)
INFO net.py: 204: res5_0_branch2b_bn_b loaded from weights file into gpu_0/res5_0_branch2b_bn_b: (512,)
INFO net.py: 204: res5_0_branch1_w loaded from weights file into gpu_0/res5_0_branch1_w: (512, 256, 1, 1)
WARNING net.py: 150: Workspace blob res5_0_branch1_w ((512, 256, 1, 1, 1)) loaded with pretrained wts (512, 256, 1, 1) after inflating the weights by center-only mode.
INFO net.py: 204: res5_0_branch1_bn_s loaded from weights file into gpu_0/res5_0_branch1_bn_s: (512,)
INFO net.py: 204: res5_0_branch1_bn_b loaded from weights file into gpu_0/res5_0_branch1_bn_b: (512,)
INFO net.py: 204: res5_1_branch2a_w loaded from weights file into gpu_0/res5_1_branch2a_w: (512, 512, 3, 3)
WARNING net.py: 150: Workspace blob res5_1_branch2a_w ((512, 512, 1, 3, 3)) loaded with pretrained wts (512, 512, 3, 3) after inflating the weights by center-only mode.
INFO net.py: 204: res5_1_branch2a_bn_s loaded from weights file into gpu_0/res5_1_branch2a_bn_s: (512,)
INFO net.py: 204: res5_1_branch2a_bn_b loaded from weights file into gpu_0/res5_1_branch2a_bn_b: (512,)
INFO net.py: 204: res5_1_branch2b_w loaded from weights file into gpu_0/res5_1_branch2b_w: (512, 512, 3, 3)
WARNING net.py: 150: Workspace blob res5_1_branch2b_w ((512, 512, 1, 3, 3)) loaded with pretrained wts (512, 512, 3, 3) after inflating the weights by center-only mode.
INFO net.py: 204: res5_1_branch2b_bn_s loaded from weights file into gpu_0/res5_1_branch2b_bn_s: (512,)
INFO net.py: 204: res5_1_branch2b_bn_b loaded from weights file into gpu_0/res5_1_branch2b_bn_b: (512,)
INFO net.py: 196: cls_score_1_w not found
INFO net.py: 196: cls_score_1_b not found
INFO net.py: 196: bbox_pred_1_w not found
INFO net.py: 196: bbox_pred_1_b not found
INFO net.py: 196: conv_fcn1_w not found
INFO net.py: 196: conv_fcn1_b not found
INFO net.py: 196: conv_fcn2_w not found
INFO net.py: 196: conv_fcn2_b not found
INFO net.py: 196: conv_fcn3_w not found
INFO net.py: 196: conv_fcn3_b not found
INFO net.py: 196: conv_fcn4_w not found
INFO net.py: 196: conv_fcn4_b not found
INFO net.py: 196: conv_fcn5_w not found
INFO net.py: 196: conv_fcn5_b not found
INFO net.py: 196: conv_fcn6_w not found
INFO net.py: 196: conv_fcn6_b not found
INFO net.py: 196: conv_fcn7_w not found
INFO net.py: 196: conv_fcn7_b not found
INFO net.py: 196: conv_fcn8_w not found
INFO net.py: 196: conv_fcn8_b not found
INFO net.py: 196: kps_score_lowres_w not found
INFO net.py: 196: kps_score_lowres_b not found
INFO net.py: 196: kps_score_prefinal_w not found
INFO net.py: 196: kps_score_prefinal_b not found
INFO net.py: 249: pred_b preserved in workspace (unused)
INFO net.py: 249: pred_w preserved in workspace (unused)
I0814 16:49:46.008280 44020 operator.cc:169] Engine CUDNN is not available for operator MaxPool.
I0814 16:49:46.014658 44020 operator.cc:169] Engine CUDNN is not available for operator MaxPool.
I0814 16:49:46.020335 44020 operator.cc:169] Engine CUDNN is not available for operator MaxPool.
I0814 16:49:46.026283 44020 operator.cc:169] Engine CUDNN is not available for operator MaxPool.
I0814 16:49:46.032645 44020 operator.cc:169] Engine CUDNN is not available for operator MaxPool.
I0814 16:49:46.038347 44020 operator.cc:169] Engine CUDNN is not available for operator MaxPool.
I0814 16:49:46.043714 44020 operator.cc:169] Engine CUDNN is not available for operator MaxPool.
I0814 16:49:46.049134 44020 operator.cc:169] Engine CUDNN is not available for operator MaxPool.
I0814 16:49:46.116132 44020 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 0.00463044 secs
INFO train_net.py: 144: Outputs saved to: /data/weiming.li/shiqi.dong/DetectAndTrack/outputs/configs/video/3d/04_R-18-3D_PTFromImNet.yaml/train/posetrack_v1.0_train/keypoint_rcnn
Traceback (most recent call last):
  File "/data/weiming.li/shiqi.dong/DetectAndTrack/lib/utils/coordinator.py", line 41, in stop_on_exception
    yield
  File "/data/weiming.li/shiqi.dong/DetectAndTrack/lib/roi_data/loader.py", line 209, in minibatch_loader2
    shared_readonly_dict, lock, mp_cur, mp_perm)
  File "/data/weiming.li/shiqi.dong/DetectAndTrack/lib/roi_data/loader.py", line 161, in _get_next_minibatch2
    blobs, valid = get_minibatch(minibatch_db)
  File "/data/weiming.li/shiqi.dong/DetectAndTrack/lib/roi_data/minibatch.py", line 56, in get_minibatch
    im_blob, im_scales = _get_image_blob(roidb)
  File "/data/weiming.li/shiqi.dong/DetectAndTrack/lib/roi_data/minibatch.py", line 84, in _get_image_blob
    im, cfg.PIXEL_MEANS, [target_size], cfg.TRAIN.MAX_SIZE)
  File "/data/weiming.li/shiqi.dong/DetectAndTrack/lib/utils/blob.py", line 73, in prep_im_for_blob
    im = im.astype(np.float32, copy=False)
AttributeError: 'NoneType' object has no attribute 'astype'
INFO loader.py: 220: Stopping mini-batch loading thread
INFO loader.py: 220: Stopping mini-batch loading thread
INFO loader.py: 220: Stopping mini-batch loading thread
INFO loader.py: 256: Stopping enqueue thread
INFO loader.py: 256: Stopping enqueue thread
INFO loader.py: 256: Stopping enqueue thread
INFO loader.py: 256: Stopping enqueue thread
INFO loader.py: 256: Stopping enqueue thread
INFO loader.py: 256: Stopping enqueue thread
INFO loader.py: 256: Stopping enqueue thread
INFO loader.py: 256: Stopping enqueue thread
INFO loader.py: 220: Stopping mini-batch loading thread
INFO loader.py: 309: Pre-filling mini-batch queue...
INFO loader.py: 313:   [0/64]
INFO loader.py: 321: Join-ing all worker threads...
INFO loader.py: 323: Join-ing <Process(Process-2, stopped)>
INFO loader.py: 323: Join-ing <Process(Process-3, stopped)>
INFO loader.py: 323: Join-ing <Process(Process-4, stopped)>
INFO loader.py: 323: Join-ing <Process(Process-5, stopped)>
INFO loader.py: 323: Join-ing <Thread(Thread-2, stopped 139693153580800)>
INFO loader.py: 323: Join-ing <Thread(Thread-3, stopped 139693038737152)>
INFO loader.py: 323: Join-ing <Thread(Thread-4, stopped 139693153580800)>
INFO loader.py: 323: Join-ing <Thread(Thread-5, stopped 139693038737152)>
INFO loader.py: 323: Join-ing <Thread(Thread-6, stopped 139693030344448)>
INFO loader.py: 323: Join-ing <Thread(Thread-7, stopped 139693153580800)>
INFO loader.py: 323: Join-ing <Thread(Thread-8, stopped 139693021951744)>
INFO loader.py: 323: Join-ing <Thread(Thread-9, stopped 139693021951744)>
/data/weiming.li/shiqi.dong/DetectAndTrack/lib/modeling/detector.py:598: RuntimeWarning: divide by zero encountered in float_scalars
  ratio = np.max((new_lr / cur_lr, cur_lr / new_lr))
INFO detector.py: 602: Changing learning rate 0.000000 -> 0.000333 at iter 0
/data/weiming.li/shiqi.dong/DetectAndTrack/lib/modeling/detector.py:613: RuntimeWarning: divide by zero encountered in float_scalars
  ratio = np.max((new_lr / cur_lr, cur_lr / new_lr))
I0814 16:49:48.402222 44020 net_async_base.cc:435] Using specified CPU pool size: 32; NUMA node id: -1
I0814 16:49:48.402253 44020 net_async_base.cc:440] Created new CPU pool, size: 32; NUMA node id: -1
E0814 16:49:48.404006 44960 net_async_base.cc:352] Failed to execute an op: DequeueBlobs
E0814 16:49:48.404012 44958 net_async_base.cc:352] Failed to execute an op: DequeueBlobs
E0814 16:49:48.404014 44963 net_async_base.cc:352] Failed to execute an op: DequeueBlobs
E0814 16:49:48.404011 44962 net_async_base.cc:352] Failed to execute an op: DequeueBlobs
E0814 16:49:48.404040 44959 net_async_base.cc:352] Failed to execute an op: DequeueBlobs
E0814 16:49:48.404011 44964 net_async_base.cc:352] Failed to execute an op: DequeueBlobs
E0814 16:49:48.404023 44965 net_async_base.cc:352] Failed to execute an op: DequeueBlobs
E0814 16:49:48.404013 44961 net_async_base.cc:352] Failed to execute an op: DequeueBlobs
WARNING workspace.py: 187: Original python traceback for operator `2` in network `keypoint_rcnn` in exception above (most recent call last):
WARNING workspace.py: 192:   File "tools/train_net.py", line 257, in <module>
WARNING workspace.py: 192:   File "tools/train_net.py", line 130, in net_trainer
WARNING workspace.py: 192:   File "tools/train_net.py", line 107, in create_model
WARNING workspace.py: 192:   File "/data/weiming.li/shiqi.dong/DetectAndTrack/lib/modeling/model_builder.py", line 61, in create
WARNING workspace.py: 192:   File "/data/weiming.li/shiqi.dong/DetectAndTrack/lib/modeling/model_builder.py", line 154, in keypoint_rcnn
WARNING workspace.py: 192:   File "/data/weiming.li/shiqi.dong/DetectAndTrack/lib/modeling/model_builder.py", line 305, in build_generic_fast_rcnn_model
WARNING workspace.py: 192:   File "/data/weiming.li/shiqi.dong/DetectAndTrack/lib/modeling/model_builder.py", line 916, in build_data_parallel_model
WARNING workspace.py: 192:   File "/data/weiming.li/shiqi.dong/DetectAndTrack/lib/modeling/model_builder.py", line 197, in _single_gpu_build_func
WARNING workspace.py: 192:   File "/data/weiming.li/shiqi.dong/DetectAndTrack/lib/modeling/ResNet3D.py", line 337, in add_ResNet18_conv4_body
WARNING workspace.py: 192:   File "/data/weiming.li/shiqi.dong/DetectAndTrack/lib/modeling/ResNet3D.py", line 261, in add_ResNet_convX_body
WARNING workspace.py: 192:   File "/data/weiming.li/.pyenv/versions/anaconda2-5.2.0/lib/python2.7/site-packages/caffe2/python/cnn.py", line 86, in ConvNd
WARNING workspace.py: 192:   File "/data/weiming.li/.pyenv/versions/anaconda2-5.2.0/lib/python2.7/site-packages/caffe2/python/brew.py", line 107, in scope_wrapper
WARNING workspace.py: 192:   File "/data/weiming.li/.pyenv/versions/anaconda2-5.2.0/lib/python2.7/site-packages/caffe2/python/helpers/conv.py", line 164, in conv_nd
WARNING workspace.py: 192:   File "/data/weiming.li/.pyenv/versions/anaconda2-5.2.0/lib/python2.7/site-packages/caffe2/python/helpers/conv.py", line 123, in _ConvBase
Traceback (most recent call last):
  File "tools/train_net.py", line 257, in <module>
    checkpoints = net_trainer()
  File "tools/train_net.py", line 174, in net_trainer
    workspace.RunNet(model.net.Proto().name)
  File "/data/weiming.li/.pyenv/versions/anaconda2-5.2.0/lib/python2.7/site-packages/caffe2/python/workspace.py", line 219, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/data/weiming.li/.pyenv/versions/anaconda2-5.2.0/lib/python2.7/site-packages/caffe2/python/workspace.py", line 180, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at pybind_state.cc:1096] success. Error running net keypoint_rcnn
```

How can I fix it? I hope anyone's help, thanks very much. @rohitgirdhar

**Comment by rohitgirdhar** [comment]
Same as #34. Please set the path to the directory where the frames are stored in `json_dataset.py`.

**Comment by Marcovaldong** [comment]
Yes, I found where the problem is by myself, then I fixed it.

**Comment by ezreal1129** [comment]
hi. @Marcovaldong ,i don't have the PoseTrackV1.0_Annots_train/test_json directory ,and the gen_posetrack.py only creat the posetrack_train/val/test.json.so how to get the PoseTrackV1.0_Annots_train/test_json directory . thank to get your help.

**Comment by ezreal1129** [comment]
@rohitgirdhar

**Comment by ezreal1129** [comment]
@ i have same problem,how to you fixed it ,can you post your json_dataset.py?

**Comment by my-hello-world** [comment]
> @ i have same problem,how to you fixed it ,can you post your json_dataset.py?

`  File "/home/vivian/HelloWorld/tracker/DetectAndTrack/tools/gen_posetrack_json.py", line 216, in _convert_mat_to_COCO_json
    with open(out_path, 'w') as fout:
11 -> 9
IOError: [Errno 2] No such file or directory: u'lib/datasets/lists/PoseTrack/v1.0/posetrack_test.json'
`

hello？？ you has fixedit，right？
