### ISSUE TITLE
AssertionError: Custom ops lib not found at '/detectandtrack/lib/build/libcaffe2_detectron_custom_ops_gpu.so'

### ISSUE THREAD

**Issue by WuZhuoran** [facebookresearch/DetectAndTrack#70]
When I try to use `test_on_single_video.py`, I get the following error.

```bash
python tools/test_on_single_video.py --cfg configs/video/2d_best/01_R101_best_hungarian-4GPU.yaml --video test.mp4 --output outputs/tracks_and_visualizations TEST.WEIGHTS 01_R101_best_hungarian-4GPU.yaml/model_final.pkl
```

Error:

```
E0425 23:20:52.268664   595 init_intrinsics_check.cc:54] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0425 23:20:52.268729   595 init_intrinsics_check.cc:54] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0425 23:20:52.268740   595 init_intrinsics_check.cc:54] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Traceback (most recent call last):
  File "tools/test_on_single_video.py", line 374, in <module>
    utils.c2.import_custom_ops()
  File "/detectandtrack/lib/utils/c2.py", line 55, in import_custom_ops
    custom_ops_lib = envu.get_custom_ops_lib()
  File "/detectandtrack/lib/utils/env.py", line 90, in get_custom_ops_lib
    'Custom ops lib not found at \'{}\''.format(custom_ops_lib)
AssertionError: Custom ops lib not found at '/detectandtrack/lib/build/libcaffe2_detectron_custom_ops_gpu.so'
```

Also, i got error during `make ops`, but it is optional so I just skip.
The make error is:

```
mkdir -p build && cd build && cmake .. && make -j20
CMake Warning at /usr/local/caffe2_build/share/cmake/Caffe2/public/gflags.cmake:2 (find_package):
  By not providing "Findgflags.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gflags", but
  CMake did not find one.

  Could not find a package configuration file provided by "gflags" with any
  of the following names:

    gflagsConfig.cmake
    gflags-config.cmake

  Add the installation prefix of "gflags" to CMAKE_PREFIX_PATH or set
  "gflags_DIR" to a directory containing one of the above files.  If "gflags"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /usr/local/caffe2_build/share/cmake/Caffe2/Caffe2Config.cmake:16 (include)
  CMakeLists.txt:8 (find_package)


-- Cannot find gflags with config files. Using legacy find.
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
CMake Warning at /usr/local/caffe2_build/share/cmake/Caffe2/public/glog.cmake:2 (find_package):
  By not providing "Findglog.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "glog", but
  CMake did not find one.

  Could not find a package configuration file provided by "glog" with any of
  the following names:

    glogConfig.cmake
    glog-config.cmake

  Add the installation prefix of "glog" to CMAKE_PREFIX_PATH or set
  "glog_DIR" to a directory containing one of the above files.  If "glog"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /usr/local/caffe2_build/share/cmake/Caffe2/Caffe2Config.cmake:30 (include)
  CMakeLists.txt:8 (find_package)


-- Cannot find glog. Using legacy find.
CMake Warning at CMakeLists.txt:13 (message):
  You are using an older version of Caffe2 (version 0.8.1).  Please consider
  moving to a newer version.


CMake Error at CMakeLists.txt:16 (include):
  include could not find load file:

    cmake/legacy/legacymake.cmake


-- Configuring incomplete, errors occurred!
See also "/detectandtrack/lib/build/CMakeFiles/CMakeOutput.log".
Makefile:13: recipe for target 'ops' failed
make: *** [ops] Error 1
```

I want to know if this is caffe2 version problem. Thank you.

**Comment by Juggernaut93** [comment]
I get the same error while building the Docker image. There are probably cmake files missing in this repo (legacymake.cmake).
