### ISSUE TITLE
ImportError: No module named libfb.py

### ISSUE THREAD

**Issue by Feynman27** [facebookresearch/DetectAndTrack#8]
I'm hitting an import error when trying to test with:

```bash
python launch.py \
	--cfg configs/video/2d_best/01_R101_best_hungarian-4GPU.yaml \
	--mode test \
	TEST.WEIGHTS pretrained_models/configs/video/2d_best/01_R101_best_hungarian.yaml/model_final.pkl
```

```bash
Traceback (most recent call last):
  File "tools/test_net.py", line 19, in <module>
    from core.rpn_generator import generate_rpn_on_range, generate_rpn_on_dataset
  File "/home/thomasbalestri/PlayGround/DetectAndTrack/lib/core/rpn_generator.py", line 21, in <module>
    from libfb.py import parutil
ImportError: No module named libfb.py
```

Is this file missing from the repo?

**Comment by rohitgirdhar** [comment]
Actually we don't use that import in this code anyway, so it can be safely commented out. I've updated the code.
